// Copyright 2015 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: src/main/protobuf/invocation_policy.proto

package invocationpolicy

import (
	strategypolicy "github.com/antoniospapantoniou/bazel-broker/internal/genproto/strategypolicy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetValue_Behavior int32

const (
	SetValue_UNDEFINED SetValue_Behavior = 0
	// Change the flag value but allow it to be overridden by explicit settings
	// from command line/config expansion/rc files.
	// Matching old flag values: append = false, overridable = true.
	SetValue_ALLOW_OVERRIDES SetValue_Behavior = 1
	// Append a new value for a repeatable flag, leave old values and allow
	// further overrides.
	// Matching old flag values: append = true, overridable = false.
	SetValue_APPEND SetValue_Behavior = 2
	// Set a final value of the flag. Any overrides provided by the user for
	// this flag will be ignored.
	// Matching old flag values: append = false, overridable = false.
	SetValue_FINAL_VALUE_IGNORE_OVERRIDES SetValue_Behavior = 3
)

// Enum value maps for SetValue_Behavior.
var (
	SetValue_Behavior_name = map[int32]string{
		0: "UNDEFINED",
		1: "ALLOW_OVERRIDES",
		2: "APPEND",
		3: "FINAL_VALUE_IGNORE_OVERRIDES",
	}
	SetValue_Behavior_value = map[string]int32{
		"UNDEFINED":                    0,
		"ALLOW_OVERRIDES":              1,
		"APPEND":                       2,
		"FINAL_VALUE_IGNORE_OVERRIDES": 3,
	}
)

func (x SetValue_Behavior) Enum() *SetValue_Behavior {
	p := new(SetValue_Behavior)
	*p = x
	return p
}

func (x SetValue_Behavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetValue_Behavior) Descriptor() protoreflect.EnumDescriptor {
	return file_src_main_protobuf_invocation_policy_proto_enumTypes[0].Descriptor()
}

func (SetValue_Behavior) Type() protoreflect.EnumType {
	return &file_src_main_protobuf_invocation_policy_proto_enumTypes[0]
}

func (x SetValue_Behavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SetValue_Behavior) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SetValue_Behavior(num)
	return nil
}

// Deprecated: Use SetValue_Behavior.Descriptor instead.
func (SetValue_Behavior) EnumDescriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{2, 0}
}

// The --invocation_policy flag takes a base64-encoded binary-serialized or text
// formatted InvocationPolicy message.
type InvocationPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order matters.
	// After expanding policies on expansion flags or flags with implicit
	// requirements, only the final policy on a specific flag will be enforced
	// onto the user's command line.
	FlagPolicies   []*FlagPolicy                  `protobuf:"bytes,1,rep,name=flag_policies,json=flagPolicies" json:"flag_policies,omitempty"`
	StrategyPolicy *strategypolicy.StrategyPolicy `protobuf:"bytes,2,opt,name=strategy_policy,json=strategyPolicy" json:"strategy_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvocationPolicy) Reset() {
	*x = InvocationPolicy{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationPolicy) ProtoMessage() {}

func (x *InvocationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationPolicy.ProtoReflect.Descriptor instead.
func (*InvocationPolicy) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{0}
}

func (x *InvocationPolicy) GetFlagPolicies() []*FlagPolicy {
	if x != nil {
		return x.FlagPolicies
	}
	return nil
}

func (x *InvocationPolicy) GetStrategyPolicy() *strategypolicy.StrategyPolicy {
	if x != nil {
		return x.StrategyPolicy
	}
	return nil
}

// A policy for controlling the value of a flag.
type FlagPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the flag to enforce this policy on.
	//
	// Note that this should be the full name of the flag, not the abbreviated
	// name of the flag. If the user specifies the abbreviated name of a flag,
	// that flag will be matched using its full name.
	//
	// The "no" prefix will not be parsed, so for boolean flags, use
	// the flag's full name and explicitly set it to true or false.
	FlagName *string `protobuf:"bytes,1,opt,name=flag_name,json=flagName" json:"flag_name,omitempty"`
	// If set, this flag policy is applied only if one of the given commands or a
	// command that inherits from one of the given commands is being run. For
	// instance, if "build" is one of the commands here, then this policy will
	// apply to any command that inherits from build, such as info, coverage, or
	// test. If empty, this flag policy is applied for all commands. This allows
	// the policy setter to add all policies to the proto without having to
	// determine which Bazel command the user is actually running. Additionally,
	// Bazel allows multiple flags to be defined by the same name, and the
	// specific flag definition is determined by the command.
	Commands []string `protobuf:"bytes,2,rep,name=commands" json:"commands,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*FlagPolicy_SetValue
	//	*FlagPolicy_UseDefault
	//	*FlagPolicy_DisallowValues
	//	*FlagPolicy_AllowValues
	Operation     isFlagPolicy_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagPolicy) Reset() {
	*x = FlagPolicy{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagPolicy) ProtoMessage() {}

func (x *FlagPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagPolicy.ProtoReflect.Descriptor instead.
func (*FlagPolicy) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{1}
}

func (x *FlagPolicy) GetFlagName() string {
	if x != nil && x.FlagName != nil {
		return *x.FlagName
	}
	return ""
}

func (x *FlagPolicy) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *FlagPolicy) GetOperation() isFlagPolicy_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *FlagPolicy) GetSetValue() *SetValue {
	if x != nil {
		if x, ok := x.Operation.(*FlagPolicy_SetValue); ok {
			return x.SetValue
		}
	}
	return nil
}

func (x *FlagPolicy) GetUseDefault() *UseDefault {
	if x != nil {
		if x, ok := x.Operation.(*FlagPolicy_UseDefault); ok {
			return x.UseDefault
		}
	}
	return nil
}

func (x *FlagPolicy) GetDisallowValues() *DisallowValues {
	if x != nil {
		if x, ok := x.Operation.(*FlagPolicy_DisallowValues); ok {
			return x.DisallowValues
		}
	}
	return nil
}

func (x *FlagPolicy) GetAllowValues() *AllowValues {
	if x != nil {
		if x, ok := x.Operation.(*FlagPolicy_AllowValues); ok {
			return x.AllowValues
		}
	}
	return nil
}

type isFlagPolicy_Operation interface {
	isFlagPolicy_Operation()
}

type FlagPolicy_SetValue struct {
	SetValue *SetValue `protobuf:"bytes,3,opt,name=set_value,json=setValue,oneof"`
}

type FlagPolicy_UseDefault struct {
	UseDefault *UseDefault `protobuf:"bytes,4,opt,name=use_default,json=useDefault,oneof"`
}

type FlagPolicy_DisallowValues struct {
	DisallowValues *DisallowValues `protobuf:"bytes,5,opt,name=disallow_values,json=disallowValues,oneof"`
}

type FlagPolicy_AllowValues struct {
	AllowValues *AllowValues `protobuf:"bytes,6,opt,name=allow_values,json=allowValues,oneof"`
}

func (*FlagPolicy_SetValue) isFlagPolicy_Operation() {}

func (*FlagPolicy_UseDefault) isFlagPolicy_Operation() {}

func (*FlagPolicy_DisallowValues) isFlagPolicy_Operation() {}

func (*FlagPolicy_AllowValues) isFlagPolicy_Operation() {}

type SetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use this value for the specified flag, overriding any default or user-set
	// value (unless behavior = APPEND for repeatable flags).
	//
	// This field is repeated for repeatable flags. It is an error to set
	// multiple values for a flag that is not actually a repeatable flag.
	// This requires at least 1 value, if even the empty string.
	//
	// If the flag allows multiple values, all of its values are replaced with the
	// value or values from the policy (i.e., no diffing or merging is performed),
	// unless behavior = APPEND (see below).
	//
	// Note that some flags are tricky. For example, some flags look like boolean
	// flags, but are actually Void expansion flags that expand into other flags.
	// The Bazel flag parser will accept "--void_flag=false", but because
	// the flag is Void, the "=false" is ignored. It can get even trickier, like
	// "--novoid_flag" which is also an expansion flag with the type Void whose
	// name is explicitly "novoid_flag" and which expands into other flags that
	// are the opposite of "--void_flag". For expansion flags, it's best to
	// explicitly override the flags they expand into.
	//
	// Other flags may be differently tricky: A flag could have a converter that
	// converts some string to a list of values, but that flag may not itself have
	// allowMultiple set to true.
	//
	// An example is "--test_tag_filters": this flag sets its converter to
	// CommaSeparatedOptionListConverter, but does not set allowMultiple to true.
	// So "--test_tag_filters=foo,bar" results in ["foo", "bar"], however
	// "--test_tag_filters=foo --test_tag_filters=bar" results in just ["bar"]
	// since the 2nd value overrides the 1st.
	//
	// Similarly, "--test_tag_filters=foo,bar --test_tag_filters=baz,qux" results
	// in ["baz", "qux"]. For flags like these, the policy should specify
	// "foo,bar" instead of separately specifying "foo" and "bar" so that the
	// converter is appropriately invoked.
	//
	// Note that the opposite is not necessarily
	// true: for a flag that specifies allowMultiple=true, "--flag=foo,bar"
	// may fail to parse or result in an unexpected value.
	FlagValue []string `protobuf:"bytes,1,rep,name=flag_value,json=flagValue" json:"flag_value,omitempty"`
	// Defines how invocation policy should interact with user settings for the
	// same flag.
	Behavior      *SetValue_Behavior `protobuf:"varint,4,opt,name=behavior,enum=blaze.invocation_policy.SetValue_Behavior" json:"behavior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{2}
}

func (x *SetValue) GetFlagValue() []string {
	if x != nil {
		return x.FlagValue
	}
	return nil
}

func (x *SetValue) GetBehavior() SetValue_Behavior {
	if x != nil && x.Behavior != nil {
		return *x.Behavior
	}
	return SetValue_UNDEFINED
}

type UseDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseDefault) Reset() {
	*x = UseDefault{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseDefault) ProtoMessage() {}

func (x *UseDefault) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseDefault.ProtoReflect.Descriptor instead.
func (*UseDefault) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{3}
}

type DisallowValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// It is an error for the user to use any of these values (that is, the Bazel
	// command will fail), unless new_value or use_default is set.
	//
	// For repeatable flags, if any one of the values in the flag matches a value
	// in the list of disallowed values, an error is thrown.
	//
	// Care must be taken for flags with complicated converters. For example,
	// it's possible for a repeated flag to be of type List<List<T>>, so that
	// "--foo=a,b --foo=c,d" results in foo=[["a","b"], ["c", "d"]]. In this case,
	// it is not possible to disallow just "b", nor will ["b", "a"] match, nor
	// will ["b", "c"] (but ["a", "b"] will still match).
	DisallowedValues []string `protobuf:"bytes,1,rep,name=disallowed_values,json=disallowedValues" json:"disallowed_values,omitempty"`
	// Types that are valid to be assigned to ReplacementValue:
	//
	//	*DisallowValues_NewValue
	//	*DisallowValues_UseDefault
	ReplacementValue isDisallowValues_ReplacementValue `protobuf_oneof:"replacement_value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DisallowValues) Reset() {
	*x = DisallowValues{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisallowValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisallowValues) ProtoMessage() {}

func (x *DisallowValues) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisallowValues.ProtoReflect.Descriptor instead.
func (*DisallowValues) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{4}
}

func (x *DisallowValues) GetDisallowedValues() []string {
	if x != nil {
		return x.DisallowedValues
	}
	return nil
}

func (x *DisallowValues) GetReplacementValue() isDisallowValues_ReplacementValue {
	if x != nil {
		return x.ReplacementValue
	}
	return nil
}

func (x *DisallowValues) GetNewValue() string {
	if x != nil {
		if x, ok := x.ReplacementValue.(*DisallowValues_NewValue); ok {
			return x.NewValue
		}
	}
	return ""
}

func (x *DisallowValues) GetUseDefault() *UseDefault {
	if x != nil {
		if x, ok := x.ReplacementValue.(*DisallowValues_UseDefault); ok {
			return x.UseDefault
		}
	}
	return nil
}

type isDisallowValues_ReplacementValue interface {
	isDisallowValues_ReplacementValue()
}

type DisallowValues_NewValue struct {
	// If set and if the value of the flag is disallowed (including the default
	// value of the flag if the user doesn't specify a value), use this value as
	// the value of the flag instead of raising an error. This does not apply to
	// repeatable flags and is ignored if the flag is a repeatable flag.
	NewValue string `protobuf:"bytes,3,opt,name=new_value,json=newValue,oneof"`
}

type DisallowValues_UseDefault struct {
	// If set and if the value of the flag is disallowed, use the default value
	// of the flag instead of raising an error. Unlike new_value, this works for
	// repeatable flags, but note that the default value for repeatable flags is
	// always empty.
	//
	// Note that it is an error to disallow the default value of the flag and
	// to set use_default, unless the flag is a repeatable flag where the
	// default value is always the empty list.
	UseDefault *UseDefault `protobuf:"bytes,4,opt,name=use_default,json=useDefault,oneof"`
}

func (*DisallowValues_NewValue) isDisallowValues_ReplacementValue() {}

func (*DisallowValues_UseDefault) isDisallowValues_ReplacementValue() {}

type AllowValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// It is an error for the user to use any value not in this list, unless
	// new_value or use_default is set.
	AllowedValues []string `protobuf:"bytes,1,rep,name=allowed_values,json=allowedValues" json:"allowed_values,omitempty"`
	// Types that are valid to be assigned to ReplacementValue:
	//
	//	*AllowValues_NewValue
	//	*AllowValues_UseDefault
	ReplacementValue isAllowValues_ReplacementValue `protobuf_oneof:"replacement_value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllowValues) Reset() {
	*x = AllowValues{}
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowValues) ProtoMessage() {}

func (x *AllowValues) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_invocation_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowValues.ProtoReflect.Descriptor instead.
func (*AllowValues) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_invocation_policy_proto_rawDescGZIP(), []int{5}
}

func (x *AllowValues) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

func (x *AllowValues) GetReplacementValue() isAllowValues_ReplacementValue {
	if x != nil {
		return x.ReplacementValue
	}
	return nil
}

func (x *AllowValues) GetNewValue() string {
	if x != nil {
		if x, ok := x.ReplacementValue.(*AllowValues_NewValue); ok {
			return x.NewValue
		}
	}
	return ""
}

func (x *AllowValues) GetUseDefault() *UseDefault {
	if x != nil {
		if x, ok := x.ReplacementValue.(*AllowValues_UseDefault); ok {
			return x.UseDefault
		}
	}
	return nil
}

type isAllowValues_ReplacementValue interface {
	isAllowValues_ReplacementValue()
}

type AllowValues_NewValue struct {
	// If set and if the value of the flag is disallowed (including the default
	// value of the flag if the user doesn't specify a value), use this value as
	// the value of the flag instead of raising an error. This does not apply to
	// repeatable flags and is ignored if the flag is a repeatable flag.
	NewValue string `protobuf:"bytes,3,opt,name=new_value,json=newValue,oneof"`
}

type AllowValues_UseDefault struct {
	// If set and if the value of the flag is disallowed, use the default value
	// of the flag instead of raising an error. Unlike new_value, this works for
	// repeatable flags, but note that the default value for repeatable flags is
	// always empty.
	//
	// Note that it is an error to disallow the default value of the flag and
	// to set use_default, unless the flag is a repeatable flag where the
	// default value is always the empty list.
	UseDefault *UseDefault `protobuf:"bytes,4,opt,name=use_default,json=useDefault,oneof"`
}

func (*AllowValues_NewValue) isAllowValues_ReplacementValue() {}

func (*AllowValues_UseDefault) isAllowValues_ReplacementValue() {}

var File_src_main_protobuf_invocation_policy_proto protoreflect.FileDescriptor

const file_src_main_protobuf_invocation_policy_proto_rawDesc = "" +
	"\n" +
	")src/main/protobuf/invocation_policy.proto\x12\x17blaze.invocation_policy\x1a'src/main/protobuf/strategy_policy.proto\"\xac\x01\n" +
	"\x10InvocationPolicy\x12H\n" +
	"\rflag_policies\x18\x01 \x03(\v2#.blaze.invocation_policy.FlagPolicyR\fflagPolicies\x12N\n" +
	"\x0fstrategy_policy\x18\x02 \x01(\v2%.blaze.strategy_policy.StrategyPolicyR\x0estrategyPolicy\"\xfb\x02\n" +
	"\n" +
	"FlagPolicy\x12\x1b\n" +
	"\tflag_name\x18\x01 \x01(\tR\bflagName\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\x12@\n" +
	"\tset_value\x18\x03 \x01(\v2!.blaze.invocation_policy.SetValueH\x00R\bsetValue\x12F\n" +
	"\vuse_default\x18\x04 \x01(\v2#.blaze.invocation_policy.UseDefaultH\x00R\n" +
	"useDefault\x12R\n" +
	"\x0fdisallow_values\x18\x05 \x01(\v2'.blaze.invocation_policy.DisallowValuesH\x00R\x0edisallowValues\x12I\n" +
	"\fallow_values\x18\x06 \x01(\v2$.blaze.invocation_policy.AllowValuesH\x00R\vallowValuesB\v\n" +
	"\toperation\"\xdb\x01\n" +
	"\bSetValue\x12\x1d\n" +
	"\n" +
	"flag_value\x18\x01 \x03(\tR\tflagValue\x12F\n" +
	"\bbehavior\x18\x04 \x01(\x0e2*.blaze.invocation_policy.SetValue.BehaviorR\bbehavior\"\\\n" +
	"\bBehavior\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\x13\n" +
	"\x0fALLOW_OVERRIDES\x10\x01\x12\n" +
	"\n" +
	"\x06APPEND\x10\x02\x12 \n" +
	"\x1cFINAL_VALUE_IGNORE_OVERRIDES\x10\x03J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"\f\n" +
	"\n" +
	"UseDefault\"\xbf\x01\n" +
	"\x0eDisallowValues\x12+\n" +
	"\x11disallowed_values\x18\x01 \x03(\tR\x10disallowedValues\x12\x1d\n" +
	"\tnew_value\x18\x03 \x01(\tH\x00R\bnewValue\x12F\n" +
	"\vuse_default\x18\x04 \x01(\v2#.blaze.invocation_policy.UseDefaultH\x00R\n" +
	"useDefaultB\x13\n" +
	"\x11replacement_valueJ\x04\b\x02\x10\x03\"\xb6\x01\n" +
	"\vAllowValues\x12%\n" +
	"\x0eallowed_values\x18\x01 \x03(\tR\rallowedValues\x12\x1d\n" +
	"\tnew_value\x18\x03 \x01(\tH\x00R\bnewValue\x12F\n" +
	"\vuse_default\x18\x04 \x01(\v2#.blaze.invocation_policy.UseDefaultH\x00R\n" +
	"useDefaultB\x13\n" +
	"\x11replacement_valueJ\x04\b\x02\x10\x03B-\n" +
	"+com.google.devtools.build.lib.runtime.proto"

var (
	file_src_main_protobuf_invocation_policy_proto_rawDescOnce sync.Once
	file_src_main_protobuf_invocation_policy_proto_rawDescData []byte
)

func file_src_main_protobuf_invocation_policy_proto_rawDescGZIP() []byte {
	file_src_main_protobuf_invocation_policy_proto_rawDescOnce.Do(func() {
		file_src_main_protobuf_invocation_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_main_protobuf_invocation_policy_proto_rawDesc), len(file_src_main_protobuf_invocation_policy_proto_rawDesc)))
	})
	return file_src_main_protobuf_invocation_policy_proto_rawDescData
}

var file_src_main_protobuf_invocation_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_main_protobuf_invocation_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_main_protobuf_invocation_policy_proto_goTypes = []any{
	(SetValue_Behavior)(0),                // 0: blaze.invocation_policy.SetValue.Behavior
	(*InvocationPolicy)(nil),              // 1: blaze.invocation_policy.InvocationPolicy
	(*FlagPolicy)(nil),                    // 2: blaze.invocation_policy.FlagPolicy
	(*SetValue)(nil),                      // 3: blaze.invocation_policy.SetValue
	(*UseDefault)(nil),                    // 4: blaze.invocation_policy.UseDefault
	(*DisallowValues)(nil),                // 5: blaze.invocation_policy.DisallowValues
	(*AllowValues)(nil),                   // 6: blaze.invocation_policy.AllowValues
	(*strategypolicy.StrategyPolicy)(nil), // 7: blaze.strategy_policy.StrategyPolicy
}
var file_src_main_protobuf_invocation_policy_proto_depIdxs = []int32{
	2, // 0: blaze.invocation_policy.InvocationPolicy.flag_policies:type_name -> blaze.invocation_policy.FlagPolicy
	7, // 1: blaze.invocation_policy.InvocationPolicy.strategy_policy:type_name -> blaze.strategy_policy.StrategyPolicy
	3, // 2: blaze.invocation_policy.FlagPolicy.set_value:type_name -> blaze.invocation_policy.SetValue
	4, // 3: blaze.invocation_policy.FlagPolicy.use_default:type_name -> blaze.invocation_policy.UseDefault
	5, // 4: blaze.invocation_policy.FlagPolicy.disallow_values:type_name -> blaze.invocation_policy.DisallowValues
	6, // 5: blaze.invocation_policy.FlagPolicy.allow_values:type_name -> blaze.invocation_policy.AllowValues
	0, // 6: blaze.invocation_policy.SetValue.behavior:type_name -> blaze.invocation_policy.SetValue.Behavior
	4, // 7: blaze.invocation_policy.DisallowValues.use_default:type_name -> blaze.invocation_policy.UseDefault
	4, // 8: blaze.invocation_policy.AllowValues.use_default:type_name -> blaze.invocation_policy.UseDefault
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_src_main_protobuf_invocation_policy_proto_init() }
func file_src_main_protobuf_invocation_policy_proto_init() {
	if File_src_main_protobuf_invocation_policy_proto != nil {
		return
	}
	file_src_main_protobuf_invocation_policy_proto_msgTypes[1].OneofWrappers = []any{
		(*FlagPolicy_SetValue)(nil),
		(*FlagPolicy_UseDefault)(nil),
		(*FlagPolicy_DisallowValues)(nil),
		(*FlagPolicy_AllowValues)(nil),
	}
	file_src_main_protobuf_invocation_policy_proto_msgTypes[4].OneofWrappers = []any{
		(*DisallowValues_NewValue)(nil),
		(*DisallowValues_UseDefault)(nil),
	}
	file_src_main_protobuf_invocation_policy_proto_msgTypes[5].OneofWrappers = []any{
		(*AllowValues_NewValue)(nil),
		(*AllowValues_UseDefault)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_main_protobuf_invocation_policy_proto_rawDesc), len(file_src_main_protobuf_invocation_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_main_protobuf_invocation_policy_proto_goTypes,
		DependencyIndexes: file_src_main_protobuf_invocation_policy_proto_depIdxs,
		EnumInfos:         file_src_main_protobuf_invocation_policy_proto_enumTypes,
		MessageInfos:      file_src_main_protobuf_invocation_policy_proto_msgTypes,
	}.Build()
	File_src_main_protobuf_invocation_policy_proto = out.File
	file_src_main_protobuf_invocation_policy_proto_goTypes = nil
	file_src_main_protobuf_invocation_policy_proto_depIdxs = nil
}
